[package]
name = "bug-graph-client"
version = "0.1.0"
authors = ["Richard Palethorpe <richiejp@f-m.fm>"]

[dependencies]
failure = "0.1"
stdweb = "0.4.8"
serde = "1"
serde_json = "1"
serde_derive = "1"
uuid = { version = "0.5", features = ["serde"] }
yew = { path = "../../yew" }
